In [1]:
import pandas as pd


df = pd.read_csv("./merged_csv/fin/방문지_fin.csv")

In [12]:
df = df.dropna(subset=['TRAVEL_ID', 'ROAD_NM_ADDR'])

In [15]:
df[df['ROAD_NM_ADDR'].str.contains('제주')].head(3)

,VISIT_AREA_ID,TRAVEL_ID,VISIT_ORDER,VISIT_AREA_NM,VISIT_START_YMD,VISIT_END_YMD,ROAD_NM_ADDR,LOTNO_ADDR,X_COORD,Y_COORD,...,RESIDENCE_TIME_MIN,VISIT_AREA_TYPE_CD,REVISIT_YN,VISIT_CHC_REASON_CD,LODGING_TYPE_CD,DGSTFN,REVISIT_INTENTION,RCMDTN_INTENTION,SGG_CD,NEW_VISIT_AREA_ID
3043,2305190002,g_g000638,2.0,제주항 연안여객터미널,2023-05-19,2023-05-19,제주특별자치도 제주시 임항로 111,제주특별자치도 제주시 건입동 918-30,126.535003,33.519593,...,90.0,9.0,Y,6.0,NaN,5.0,5.0,5.0,NaN,35579
3092,2305230001,g_g000638,51.0,제주항 제6부두,2023-05-23,2023-05-23,제주특별자치도 제주시 임항로 191,제주특별자치도 제주시 건입동 908-1,126.543248,33.523555,...,0.0,9.0,Y,6.0,NaN,5.0,5.0,5.0,NaN,35581
26479,2309090002,g_g012228,2.0,제주 국제공항,2023-09-09,2023-09-09,제주특별자치도 제주시 공항로 2,제주특별자치도 제주시 용담2동 2002,126.492769,33.507079,...,30.0,9.0,Y,11.0,NaN,4.0,4.0,4.0,NaN,34947

In [33]:
df.groupby('NEW_VISIT_AREA_ID')['NEW_VISIT_AREA_ID'].count().sort_values()

NEW_VISIT_AREA_ID
1            1
22280        1
38638        1
22278        1
22277        1
         ...
20760      377
19263      496
5924       888
34947     1937
2500     22335
Name: NEW_VISIT_AREA_ID, Length: 47130, dtype: int64